export interface AlertItem {
    firstOccurrence: string;
    lastOccurrence: string;
    victimIP: string;
    attackerIP: string;
    assetIP: string;
    level1Type: string;
    level2Type: string;
    threatName: string;
    ioc: string;
    attackResult: string;
    threatLevel: string;
    count: number | string;
    attackStage: string;
    assetGroup: string;
    xffProxy: string;
    uri: string;
    cascadeUnit: string;
    status: string;
    hostDomain: string;
    source: string;
    attackOrg: string;
    attackMethod: string;
    httpStatus: string;
    attackDimension: string;
    isWhitelist: string;
    payload: string;
    requestHeader: string;
    requestBody: string;
    responseHeader: string;
    responseBody: string;
    webshellContent: string;
    responsiblePerson: string;
    assetTags: string;
    assetName: string;
    isKeyFocus: string;
    attackerGeo: string;
    eventReported: string;
    isRead: string;
    attackerAssetGroup: string;
    victimAssetGroup: string;
    alertTags: string;
    srcIP: string;
    dstIP: string;
    srcPort: number | string;
    dstPort: number | string;
    protocol: string;
    srcMAC: string;
    dstMAC: string;
    vlan: string;
    alertID: string;
    username: string;
    password: string;
}

export const getAlertData = (): Promise<{ data: AlertItem[] }> => {
    return new Promise((resolve) => {
        setTimeout(() => {
            resolve({
                data: [
                    {
                        firstOccurrence: '2025-04-02 00:58:32',
                        lastOccurrence: '2025-04-02 22:58:55',
                        victimIP: '192.168.130.2',
                        attackerIP: '221.204.66.204',
                        assetIP: '192.168.130.2',
                        level1Type: '攻击利用',
                        level2Type: '代理工具',
                        threatName: '发现远程连接工具ToDesk活动',
                        ioc: '0x5dde',
                        attackResult: '企图',
                        threatLevel: '中危',
                        count: 30,
                        attackStage: '入侵',
                        assetGroup: '未分配资产组',
                        xffProxy: '',
                        uri: '/api/login',
                        cascadeUnit: '本级',
                        status: '未处置',
                        hostDomain: '',
                        source: '流量探针2',
                        attackOrg: 'menuPass,Strider,Soft Cell,MuddyWater,APT39,Turla,APT28,APT3,Lazarus Group',
                        attackMethod: '连接代理',
                        httpStatus: '',
                        attackDimension: '外部攻击',
                        isWhitelist: '否',
                        payload:'',
                        requestHeader: '{ "User-Agent": "Mozilla/5.0" }',
                        requestBody: '{"username":"admin","password":"test"}',
                        responseHeader: '{ "Content-Type": "text/html" }',
                        responseBody: '',
                        webshellContent: '',
                        responsiblePerson: '张三',
                        assetTags: '核心资产',
                        assetName: 'DB_Server',
                        isKeyFocus: '是',
                        attackerGeo: '中国·北京',
                        eventReported: '未上报',
                        isRead: '未读',
                        attackerAssetGroup: '外部IP',
                        victimAssetGroup: '内部IP',
                        alertTags: '紧急',
                        srcIP: '192.168.130.2',
                        dstIP: '221.204.66.204',
                        srcPort: 21590,
                        dstPort: 53,
                        protocol: 'dns',
                        srcMAC: '60:de:f3:40:62:0f',
                        dstMAC: 'dc:36:43:e2:fc:bf',
                        vlan: '0x68',
                        alertID: '20250402_c90d148f623f9705184efb5dd2e0333e',
                        username: 'admin',
                        password: '********'
                    },
                    {
                        firstOccurrence: '2025-04-02 08:14:16',
                        lastOccurrence: '2025-04-02 22:11:41',
                        victimIP: '10.14.5.168',
                        attackerIP: '8.8.8.8',
                        assetIP: '10.14.5.168',
                        level1Type: '攻击利用',
                        level2Type: '代理工具',
                        threatName: '发现远程连接工具raylink活动',
                        ioc: '0x6011',
                        attackResult: '企图',
                        threatLevel: '中危',
                        count: 3,
                        attackStage: '入侵',
                        assetGroup: '未分配资产组',
                        xffProxy: '',
                        uri: '/api/login',
                        cascadeUnit: '本级',
                        status: '未处置',
                        hostDomain: '',
                        source: '流量探针2',
                        attackOrg: 'Soft Cell,Night Dragon,Axiom',
                        attackMethod: '利用面向公众的应用程序',
                        httpStatus: '',
                        attackDimension: '外部攻击',
                        isWhitelist: '否',
                        payload:'',
                        requestHeader: '{ "User-Agent": "Chrome" }',
                        requestBody: '{"token":"123456"}',
                        responseHeader: '{ "Set-Cookie": "session=abc" }',
                        responseBody: '',
                        webshellContent: '',
                        responsiblePerson: '李四',
                        assetTags: '生产服务器',
                        assetName: 'Web_Server',
                        isKeyFocus: '否',
                        attackerGeo: '美国·加州',
                        eventReported: '未上报',
                        isRead: '已读',
                        attackerAssetGroup: '外部IP',
                        victimAssetGroup: '内部IP',
                        alertTags: '高危告警',
                        srcIP: '10.14.5.168',
                        dstIP: '8.8.8.8',
                        srcPort: 50241,
                        dstPort: 443,
                        protocol: 'ssl',
                        srcMAC: '00:1A:2B:3C:4D:5E',
                        dstMAC: '00:0D:3C:4E:5F:6A',
                        vlan: '100',
                        alertID: '20250402_95a8cf973392002e61118474c978ba71',
                        username: 'root',
                        password: '********'
                    },
                    // 更多类似结构...
                    {
                        firstOccurrence: '2025-04-02 10:12:00',
                        lastOccurrence: '2025-04-02 12:00:00',
                        victimIP: '10.10.10.10',
                        attackerIP: '1.1.1.1',
                        assetIP: '10.10.10.10',
                        level1Type: '攻击利用',
                        level2Type: 'WebShell',
                        threatName: '疑似webshell通信',
                        ioc: '0x7f3a',
                        attackResult: '成功',
                        threatLevel: '高危',
                        count: 1,
                        attackStage: '渗透',
                        assetGroup: 'DMZ资产组',
                        xffProxy: '',
                        uri: '',
                        cascadeUnit: '总部',
                        status: '已处置',
                        hostDomain: 'example.com',
                        source: 'WAF',
                        attackOrg: 'Lazarus Group',
                        attackMethod: 'webshell上传',
                        httpStatus: '200',
                        attackDimension: '外部攻击',
                        isWhitelist: '否',
                        payload: '恶意载荷内容...',
                        requestHeader: '{ "Referer": "" }',
                        requestBody: 'cmd=id',
                        responseHeader: '{ "Location": "/redirect.php" }',
                        responseBody: 'root:x:0:0::/root:/bin/bash',
                        webshellContent: '',
                        responsiblePerson: '王五',
                        assetTags: '业务系统',
                        assetName: 'Web_Server',
                        isKeyFocus: '是',
                        attackerGeo: '新加坡',
                        eventReported: '已上报',
                        isRead: '未读',
                        attackerAssetGroup: '外部IP',
                        victimAssetGroup: '内部IP',
                        alertTags: '紧急',
                        srcIP: '10.10.10.10',
                        dstIP: '1.1.1.1',
                        srcPort: 50001,
                        dstPort: 80,
                        protocol: 'tcp',
                        srcMAC: '00:1B:44:11:3A:B7',
                        dstMAC: '00:00:5E:00:01:01',
                        vlan: '100',
                        alertID: '20250402_abcd1234',
                        username: 'user',
                        password: '********'
                    },
                    // 更多类似结构...
                    {
                        firstOccurrence: '2025-04-02 10:12:00',
                        lastOccurrence: '2025-04-02 12:00:00',
                        victimIP: '10.10.10.10',
                        attackerIP: '1.1.1.1',
                        assetIP: '10.10.10.10',
                        level1Type: '攻击利用',
                        level2Type: 'WebShell',
                        threatName: '疑似webshell通信',
                        ioc: '0x7f3a',
                        attackResult: '成功',
                        threatLevel: '高危',
                        count: 1,
                        attackStage: '渗透',
                        assetGroup: 'DMZ资产组',
                        xffProxy: '',
                        uri: '',
                        cascadeUnit: '总部',
                        status: '已处置',
                        hostDomain: 'example.com',
                        source: 'WAF',
                        attackOrg: 'Lazarus Group',
                        attackMethod: 'webshell上传',
                        httpStatus: '200',
                        attackDimension: '外部攻击',
                        isWhitelist: '否',
                        payload: '恶意载荷内容...',
                        requestHeader: '{ "Referer": "" }',
                        requestBody: 'cmd=id',
                        responseHeader: '{ "Location": "/redirect.php" }',
                        responseBody: 'root:x:0:0::/root:/bin/bash',
                        webshellContent: '',
                        responsiblePerson: '王五',
                        assetTags: '业务系统',
                        assetName: 'Web_Server',
                        isKeyFocus: '是',
                        attackerGeo: '新加坡',
                        eventReported: '已上报',
                        isRead: '未读',
                        attackerAssetGroup: '外部IP',
                        victimAssetGroup: '内部IP',
                        alertTags: '紧急',
                        srcIP: '10.10.10.10',
                        dstIP: '1.1.1.1',
                        srcPort: 50001,
                        dstPort: 80,
                        protocol: 'tcp',
                        srcMAC: '00:1B:44:11:3A:B7',
                        dstMAC: '00:00:5E:00:01:01',
                        vlan: '100',
                        alertID: '20250402_abcd1234',
                        username: 'user',
                        password: '********'
                    },
                    // 更多类似结构...
                    {
                        firstOccurrence: '2025-04-02 10:12:00',
                        lastOccurrence: '2025-04-02 12:00:00',
                        victimIP: '10.10.10.10',
                        attackerIP: '1.1.1.1',
                        assetIP: '10.10.10.10',
                        level1Type: '攻击利用',
                        level2Type: 'WebShell',
                        threatName: '疑似webshell通信',
                        ioc: '0x7f3a',
                        attackResult: '成功',
                        threatLevel: '高危',
                        count: 1,
                        attackStage: '渗透',
                        assetGroup: 'DMZ资产组',
                        xffProxy: '',
                        uri: '',
                        cascadeUnit: '总部',
                        status: '已处置',
                        hostDomain: 'example.com',
                        source: 'WAF',
                        attackOrg: 'Lazarus Group',
                        attackMethod: 'webshell上传',
                        httpStatus: '200',
                        attackDimension: '外部攻击',
                        isWhitelist: '否',
                        payload: '恶意载荷内容...',
                        requestHeader: '{ "Referer": "" }',
                        requestBody: 'cmd=id',
                        responseHeader: '{ "Location": "/redirect.php" }',
                        responseBody: 'root:x:0:0::/root:/bin/bash',
                        webshellContent: '',
                        responsiblePerson: '王五',
                        assetTags: '业务系统',
                        assetName: 'Web_Server',
                        isKeyFocus: '是',
                        attackerGeo: '新加坡',
                        eventReported: '已上报',
                        isRead: '未读',
                        attackerAssetGroup: '外部IP',
                        victimAssetGroup: '内部IP',
                        alertTags: '紧急',
                        srcIP: '10.10.10.10',
                        dstIP: '1.1.1.1',
                        srcPort: 50001,
                        dstPort: 80,
                        protocol: 'tcp',
                        srcMAC: '00:1B:44:11:3A:B7',
                        dstMAC: '00:00:5E:00:01:01',
                        vlan: '100',
                        alertID: '20250402_abcd1234',
                        username: 'user',
                        password: '********'
                    },
                    // 更多类似结构...
                    {
                        firstOccurrence: '2025-04-02 10:12:00',
                        lastOccurrence: '2025-04-02 12:00:00',
                        victimIP: '10.10.10.10',
                        attackerIP: '1.1.1.1',
                        assetIP: '10.10.10.10',
                        level1Type: '攻击利用',
                        level2Type: 'WebShell',
                        threatName: '疑似webshell通信',
                        ioc: '0x7f3a',
                        attackResult: '成功',
                        threatLevel: '高危',
                        count: 1,
                        attackStage: '渗透',
                        assetGroup: 'DMZ资产组',
                        xffProxy: '',
                        uri: '',
                        cascadeUnit: '总部',
                        status: '已处置',
                        hostDomain: 'example.com',
                        source: 'WAF',
                        attackOrg: 'Lazarus Group',
                        attackMethod: 'webshell上传',
                        httpStatus: '200',
                        attackDimension: '外部攻击',
                        isWhitelist: '否',
                        payload: '恶意载荷内容...',
                        requestHeader: '{ "Referer": "" }',
                        requestBody: 'cmd=id',
                        responseHeader: '{ "Location": "/redirect.php" }',
                        responseBody: 'root:x:0:0::/root:/bin/bash',
                        webshellContent: '',
                        responsiblePerson: '王五',
                        assetTags: '业务系统',
                        assetName: 'Web_Server',
                        isKeyFocus: '是',
                        attackerGeo: '新加坡',
                        eventReported: '已上报',
                        isRead: '未读',
                        attackerAssetGroup: '外部IP',
                        victimAssetGroup: '内部IP',
                        alertTags: '紧急',
                        srcIP: '10.10.10.10',
                        dstIP: '1.1.1.1',
                        srcPort: 50001,
                        dstPort: 80,
                        protocol: 'tcp',
                        srcMAC: '00:1B:44:11:3A:B7',
                        dstMAC: '00:00:5E:00:01:01',
                        vlan: '100',
                        alertID: '20250402_abcd1234',
                        username: 'user',
                        password: '********'
                    },
                    // 更多类似结构...
                    {
                        firstOccurrence: '2025-04-02 10:12:00',
                        lastOccurrence: '2025-04-02 12:00:00',
                        victimIP: '10.10.10.10',
                        attackerIP: '1.1.1.1',
                        assetIP: '10.10.10.10',
                        level1Type: '攻击利用',
                        level2Type: 'WebShell',
                        threatName: '疑似webshell通信',
                        ioc: '0x7f3a',
                        attackResult: '成功',
                        threatLevel: '高危',
                        count: 1,
                        attackStage: '渗透',
                        assetGroup: 'DMZ资产组',
                        xffProxy: '',
                        uri: '',
                        cascadeUnit: '总部',
                        status: '已处置',
                        hostDomain: 'example.com',
                        source: 'WAF',
                        attackOrg: 'Lazarus Group',
                        attackMethod: 'webshell上传',
                        httpStatus: '200',
                        attackDimension: '外部攻击',
                        isWhitelist: '否',
                        payload: '恶意载荷内容...',
                        requestHeader: '{ "Referer": "" }',
                        requestBody: 'cmd=id',
                        responseHeader: '{ "Location": "/redirect.php" }',
                        responseBody: 'root:x:0:0::/root:/bin/bash',
                        webshellContent: '',
                        responsiblePerson: '王五',
                        assetTags: '业务系统',
                        assetName: 'Web_Server',
                        isKeyFocus: '是',
                        attackerGeo: '新加坡',
                        eventReported: '已上报',
                        isRead: '未读',
                        attackerAssetGroup: '外部IP',
                        victimAssetGroup: '内部IP',
                        alertTags: '紧急',
                        srcIP: '10.10.10.10',
                        dstIP: '1.1.1.1',
                        srcPort: 50001,
                        dstPort: 80,
                        protocol: 'tcp',
                        srcMAC: '00:1B:44:11:3A:B7',
                        dstMAC: '00:00:5E:00:01:01',
                        vlan: '100',
                        alertID: '20250402_abcd1234',
                        username: 'user',
                        password: '********'
                    },
                    // 更多类似结构...
                    {
                        firstOccurrence: '2025-04-02 10:12:00',
                        lastOccurrence: '2025-04-02 12:00:00',
                        victimIP: '10.10.10.10',
                        attackerIP: '1.1.1.1',
                        assetIP: '10.10.10.10',
                        level1Type: '攻击利用',
                        level2Type: 'WebShell',
                        threatName: '疑似webshell通信',
                        ioc: '0x7f3a',
                        attackResult: '成功',
                        threatLevel: '高危',
                        count: 1,
                        attackStage: '渗透',
                        assetGroup: 'DMZ资产组',
                        xffProxy: '',
                        uri: '',
                        cascadeUnit: '总部',
                        status: '已处置',
                        hostDomain: 'example.com',
                        source: 'WAF',
                        attackOrg: 'Lazarus Group',
                        attackMethod: 'webshell上传',
                        httpStatus: '200',
                        attackDimension: '外部攻击',
                        isWhitelist: '否',
                        payload: '恶意载荷内容...',
                        requestHeader: '{ "Referer": "" }',
                        requestBody: 'cmd=id',
                        responseHeader: '{ "Location": "/redirect.php" }',
                        responseBody: 'root:x:0:0::/root:/bin/bash',
                        webshellContent: '',
                        responsiblePerson: '王五',
                        assetTags: '业务系统',
                        assetName: 'Web_Server',
                        isKeyFocus: '是',
                        attackerGeo: '新加坡',
                        eventReported: '已上报',
                        isRead: '未读',
                        attackerAssetGroup: '外部IP',
                        victimAssetGroup: '内部IP',
                        alertTags: '紧急',
                        srcIP: '10.10.10.10',
                        dstIP: '1.1.1.1',
                        srcPort: 50001,
                        dstPort: 80,
                        protocol: 'tcp',
                        srcMAC: '00:1B:44:11:3A:B7',
                        dstMAC: '00:00:5E:00:01:01',
                        vlan: '100',
                        alertID: '20250402_abcd1234',
                        username: 'user',
                        password: '********'
                    },
                    // 更多类似结构...
                    {
                        firstOccurrence: '2025-04-02 10:12:00',
                        lastOccurrence: '2025-04-02 12:00:00',
                        victimIP: '10.10.10.10',
                        attackerIP: '1.1.1.1',
                        assetIP: '10.10.10.10',
                        level1Type: '攻击利用',
                        level2Type: 'WebShell',
                        threatName: '疑似webshell通信',
                        ioc: '0x7f3a',
                        attackResult: '成功',
                        threatLevel: '高危',
                        count: 1,
                        attackStage: '渗透',
                        assetGroup: 'DMZ资产组',
                        xffProxy: '',
                        uri: '',
                        cascadeUnit: '总部',
                        status: '已处置',
                        hostDomain: 'example.com',
                        source: 'WAF',
                        attackOrg: 'Lazarus Group',
                        attackMethod: 'webshell上传',
                        httpStatus: '200',
                        attackDimension: '外部攻击',
                        isWhitelist: '否',
                        payload: '恶意载荷内容...',
                        requestHeader: '{ "Referer": "" }',
                        requestBody: 'cmd=id',
                        responseHeader: '{ "Location": "/redirect.php" }',
                        responseBody: 'root:x:0:0::/root:/bin/bash',
                        webshellContent: '',
                        responsiblePerson: '王五',
                        assetTags: '业务系统',
                        assetName: 'Web_Server',
                        isKeyFocus: '是',
                        attackerGeo: '新加坡',
                        eventReported: '已上报',
                        isRead: '未读',
                        attackerAssetGroup: '外部IP',
                        victimAssetGroup: '内部IP',
                        alertTags: '紧急',
                        srcIP: '10.10.10.10',
                        dstIP: '1.1.1.1',
                        srcPort: 50001,
                        dstPort: 80,
                        protocol: 'tcp',
                        srcMAC: '00:1B:44:11:3A:B7',
                        dstMAC: '00:00:5E:00:01:01',
                        vlan: '100',
                        alertID: '20250402_abcd1234',
                        username: 'user',
                        password: '********'
                    },
                    // 更多类似结构...
                    {
                        firstOccurrence: '2025-04-02 10:12:00',
                        lastOccurrence: '2025-04-02 12:00:00',
                        victimIP: '10.10.10.10',
                        attackerIP: '1.1.1.1',
                        assetIP: '10.10.10.10',
                        level1Type: '攻击利用',
                        level2Type: 'WebShell',
                        threatName: '疑似webshell通信',
                        ioc: '0x7f3a',
                        attackResult: '成功',
                        threatLevel: '高危',
                        count: 1,
                        attackStage: '渗透',
                        assetGroup: 'DMZ资产组',
                        xffProxy: '',
                        uri: '',
                        cascadeUnit: '总部',
                        status: '已处置',
                        hostDomain: 'example.com',
                        source: 'WAF',
                        attackOrg: 'Lazarus Group',
                        attackMethod: 'webshell上传',
                        httpStatus: '200',
                        attackDimension: '外部攻击',
                        isWhitelist: '否',
                        payload: '恶意载荷内容...',
                        requestHeader: '{ "Referer": "" }',
                        requestBody: 'cmd=id',
                        responseHeader: '{ "Location": "/redirect.php" }',
                        responseBody: 'root:x:0:0::/root:/bin/bash',
                        webshellContent: '',
                        responsiblePerson: '王五',
                        assetTags: '业务系统',
                        assetName: 'Web_Server',
                        isKeyFocus: '是',
                        attackerGeo: '新加坡',
                        eventReported: '已上报',
                        isRead: '未读',
                        attackerAssetGroup: '外部IP',
                        victimAssetGroup: '内部IP',
                        alertTags: '紧急',
                        srcIP: '10.10.10.10',
                        dstIP: '1.1.1.1',
                        srcPort: 50001,
                        dstPort: 80,
                        protocol: 'tcp',
                        srcMAC: '00:1B:44:11:3A:B7',
                        dstMAC: '00:00:5E:00:01:01',
                        vlan: '100',
                        alertID: '20250402_abcd1234',
                        username: 'user',
                        password: '********'
                    },
                    // 更多类似结构...
                    {
                        firstOccurrence: '2025-04-02 10:12:00',
                        lastOccurrence: '2025-04-02 12:00:00',
                        victimIP: '10.10.10.10',
                        attackerIP: '1.1.1.1',
                        assetIP: '10.10.10.10',
                        level1Type: '攻击利用',
                        level2Type: 'WebShell',
                        threatName: '疑似webshell通信',
                        ioc: '0x7f3a',
                        attackResult: '成功',
                        threatLevel: '高危',
                        count: 1,
                        attackStage: '渗透',
                        assetGroup: 'DMZ资产组',
                        xffProxy: '',
                        uri: '',
                        cascadeUnit: '总部',
                        status: '已处置',
                        hostDomain: 'example.com',
                        source: 'WAF',
                        attackOrg: 'Lazarus Group',
                        attackMethod: 'webshell上传',
                        httpStatus: '200',
                        attackDimension: '外部攻击',
                        isWhitelist: '否',
                        payload: '恶意载荷内容...',
                        requestHeader: '{ "Referer": "" }',
                        requestBody: 'cmd=id',
                        responseHeader: '{ "Location": "/redirect.php" }',
                        responseBody: 'root:x:0:0::/root:/bin/bash',
                        webshellContent: '',
                        responsiblePerson: '王五',
                        assetTags: '业务系统',
                        assetName: 'Web_Server',
                        isKeyFocus: '是',
                        attackerGeo: '新加坡',
                        eventReported: '已上报',
                        isRead: '未读',
                        attackerAssetGroup: '外部IP',
                        victimAssetGroup: '内部IP',
                        alertTags: '紧急',
                        srcIP: '10.10.10.10',
                        dstIP: '1.1.1.1',
                        srcPort: 50001,
                        dstPort: 80,
                        protocol: 'tcp',
                        srcMAC: '00:1B:44:11:3A:B7',
                        dstMAC: '00:00:5E:00:01:01',
                        vlan: '100',
                        alertID: '20250402_abcd1234',
                        username: 'user',
                        password: '********'
                    },
                    // 更多类似结构...
                    {
                        firstOccurrence: '2025-04-02 10:12:00',
                        lastOccurrence: '2025-04-02 12:00:00',
                        victimIP: '10.10.10.10',
                        attackerIP: '1.1.1.1',
                        assetIP: '10.10.10.10',
                        level1Type: '攻击利用',
                        level2Type: 'WebShell',
                        threatName: '疑似webshell通信',
                        ioc: '0x7f3a',
                        attackResult: '成功',
                        threatLevel: '高危',
                        count: 1,
                        attackStage: '渗透',
                        assetGroup: 'DMZ资产组',
                        xffProxy: '',
                        uri: '',
                        cascadeUnit: '总部',
                        status: '已处置',
                        hostDomain: 'example.com',
                        source: 'WAF',
                        attackOrg: 'Lazarus Group',
                        attackMethod: 'webshell上传',
                        httpStatus: '200',
                        attackDimension: '外部攻击',
                        isWhitelist: '否',
                        payload: '恶意载荷内容...',
                        requestHeader: '{ "Referer": "" }',
                        requestBody: 'cmd=id',
                        responseHeader: '{ "Location": "/redirect.php" }',
                        responseBody: 'root:x:0:0::/root:/bin/bash',
                        webshellContent: '',
                        responsiblePerson: '王五',
                        assetTags: '业务系统',
                        assetName: 'Web_Server',
                        isKeyFocus: '是',
                        attackerGeo: '新加坡',
                        eventReported: '已上报',
                        isRead: '未读',
                        attackerAssetGroup: '外部IP',
                        victimAssetGroup: '内部IP',
                        alertTags: '紧急',
                        srcIP: '10.10.10.10',
                        dstIP: '1.1.1.1',
                        srcPort: 50001,
                        dstPort: 80,
                        protocol: 'tcp',
                        srcMAC: '00:1B:44:11:3A:B7',
                        dstMAC: '00:00:5E:00:01:01',
                        vlan: '100',
                        alertID: '20250402_abcd1234',
                        username: 'user',
                        password: '********'
                    },
                    // 更多类似结构...
                    {
                        firstOccurrence: '2025-04-02 10:12:00',
                        lastOccurrence: '2025-04-02 12:00:00',
                        victimIP: '10.10.10.10',
                        attackerIP: '1.1.1.1',
                        assetIP: '10.10.10.10',
                        level1Type: '攻击利用',
                        level2Type: 'WebShell',
                        threatName: '疑似webshell通信',
                        ioc: '0x7f3a',
                        attackResult: '成功',
                        threatLevel: '高危',
                        count: 1,
                        attackStage: '渗透',
                        assetGroup: 'DMZ资产组',
                        xffProxy: '',
                        uri: '',
                        cascadeUnit: '总部',
                        status: '已处置',
                        hostDomain: 'example.com',
                        source: 'WAF',
                        attackOrg: 'Lazarus Group',
                        attackMethod: 'webshell上传',
                        httpStatus: '200',
                        attackDimension: '外部攻击',
                        isWhitelist: '否',
                        payload: '恶意载荷内容...',
                        requestHeader: '{ "Referer": "" }',
                        requestBody: 'cmd=id',
                        responseHeader: '{ "Location": "/redirect.php" }',
                        responseBody: 'root:x:0:0::/root:/bin/bash',
                        webshellContent: '',
                        responsiblePerson: '王五',
                        assetTags: '业务系统',
                        assetName: 'Web_Server',
                        isKeyFocus: '是',
                        attackerGeo: '新加坡',
                        eventReported: '已上报',
                        isRead: '未读',
                        attackerAssetGroup: '外部IP',
                        victimAssetGroup: '内部IP',
                        alertTags: '紧急',
                        srcIP: '10.10.10.10',
                        dstIP: '1.1.1.1',
                        srcPort: 50001,
                        dstPort: 80,
                        protocol: 'tcp',
                        srcMAC: '00:1B:44:11:3A:B7',
                        dstMAC: '00:00:5E:00:01:01',
                        vlan: '100',
                        alertID: '20250402_abcd1234',
                        username: 'user',
                        password: '********'
                    },
                    // 更多类似结构...
                    {
                        firstOccurrence: '2025-04-02 10:12:00',
                        lastOccurrence: '2025-04-02 12:00:00',
                        victimIP: '10.10.10.10',
                        attackerIP: '1.1.1.1',
                        assetIP: '10.10.10.10',
                        level1Type: '攻击利用',
                        level2Type: 'WebShell',
                        threatName: '疑似webshell通信',
                        ioc: '0x7f3a',
                        attackResult: '成功',
                        threatLevel: '高危',
                        count: 1,
                        attackStage: '渗透',
                        assetGroup: 'DMZ资产组',
                        xffProxy: '',
                        uri: '',
                        cascadeUnit: '总部',
                        status: '已处置',
                        hostDomain: 'example.com',
                        source: 'WAF',
                        attackOrg: 'Lazarus Group',
                        attackMethod: 'webshell上传',
                        httpStatus: '200',
                        attackDimension: '外部攻击',
                        isWhitelist: '否',
                        payload: '恶意载荷内容...',
                        requestHeader: '{ "Referer": "" }',
                        requestBody: 'cmd=id',
                        responseHeader: '{ "Location": "/redirect.php" }',
                        responseBody: 'root:x:0:0::/root:/bin/bash',
                        webshellContent: '',
                        responsiblePerson: '王五',
                        assetTags: '业务系统',
                        assetName: 'Web_Server',
                        isKeyFocus: '是',
                        attackerGeo: '新加坡',
                        eventReported: '已上报',
                        isRead: '未读',
                        attackerAssetGroup: '外部IP',
                        victimAssetGroup: '内部IP',
                        alertTags: '紧急',
                        srcIP: '10.10.10.10',
                        dstIP: '1.1.1.1',
                        srcPort: 50001,
                        dstPort: 80,
                        protocol: 'tcp',
                        srcMAC: '00:1B:44:11:3A:B7',
                        dstMAC: '00:00:5E:00:01:01',
                        vlan: '100',
                        alertID: '20250402_abcd1234',
                        username: 'user',
                        password: '********'
                    },
                    // 更多类似结构...
                    {
                        firstOccurrence: '2025-04-02 10:12:00',
                        lastOccurrence: '2025-04-02 12:00:00',
                        victimIP: '10.10.10.10',
                        attackerIP: '1.1.1.1',
                        assetIP: '10.10.10.10',
                        level1Type: '攻击利用',
                        level2Type: 'WebShell',
                        threatName: '疑似webshell通信',
                        ioc: '0x7f3a',
                        attackResult: '成功',
                        threatLevel: '高危',
                        count: 1,
                        attackStage: '渗透',
                        assetGroup: 'DMZ资产组',
                        xffProxy: '',
                        uri: '',
                        cascadeUnit: '总部',
                        status: '已处置',
                        hostDomain: 'example.com',
                        source: 'WAF',
                        attackOrg: 'Lazarus Group',
                        attackMethod: 'webshell上传',
                        httpStatus: '200',
                        attackDimension: '外部攻击',
                        isWhitelist: '否',
                        payload: '恶意载荷内容...',
                        requestHeader: '{ "Referer": "" }',
                        requestBody: 'cmd=id',
                        responseHeader: '{ "Location": "/redirect.php" }',
                        responseBody: 'root:x:0:0::/root:/bin/bash',
                        webshellContent: '',
                        responsiblePerson: '王五',
                        assetTags: '业务系统',
                        assetName: 'Web_Server',
                        isKeyFocus: '是',
                        attackerGeo: '新加坡',
                        eventReported: '已上报',
                        isRead: '未读',
                        attackerAssetGroup: '外部IP',
                        victimAssetGroup: '内部IP',
                        alertTags: '紧急',
                        srcIP: '10.10.10.10',
                        dstIP: '1.1.1.1',
                        srcPort: 50001,
                        dstPort: 80,
                        protocol: 'tcp',
                        srcMAC: '00:1B:44:11:3A:B7',
                        dstMAC: '00:00:5E:00:01:01',
                        vlan: '100',
                        alertID: '20250402_abcd1234',
                        username: 'user',
                        password: '********'
                    },
                    // 更多类似结构...
                    {
                        firstOccurrence: '2025-04-02 10:12:00',
                        lastOccurrence: '2025-04-02 12:00:00',
                        victimIP: '10.10.10.10',
                        attackerIP: '1.1.1.1',
                        assetIP: '10.10.10.10',
                        level1Type: '攻击利用',
                        level2Type: 'WebShell',
                        threatName: '疑似webshell通信',
                        ioc: '0x7f3a',
                        attackResult: '成功',
                        threatLevel: '高危',
                        count: 1,
                        attackStage: '渗透',
                        assetGroup: 'DMZ资产组',
                        xffProxy: '',
                        uri: '',
                        cascadeUnit: '总部',
                        status: '已处置',
                        hostDomain: 'example.com',
                        source: 'WAF',
                        attackOrg: 'Lazarus Group',
                        attackMethod: 'webshell上传',
                        httpStatus: '200',
                        attackDimension: '外部攻击',
                        isWhitelist: '否',
                        payload: '恶意载荷内容...',
                        requestHeader: '{ "Referer": "" }',
                        requestBody: 'cmd=id',
                        responseHeader: '{ "Location": "/redirect.php" }',
                        responseBody: 'root:x:0:0::/root:/bin/bash',
                        webshellContent: '',
                        responsiblePerson: '王五',
                        assetTags: '业务系统',
                        assetName: 'Web_Server',
                        isKeyFocus: '是',
                        attackerGeo: '新加坡',
                        eventReported: '已上报',
                        isRead: '未读',
                        attackerAssetGroup: '外部IP',
                        victimAssetGroup: '内部IP',
                        alertTags: '紧急',
                        srcIP: '10.10.10.10',
                        dstIP: '1.1.1.1',
                        srcPort: 50001,
                        dstPort: 80,
                        protocol: 'tcp',
                        srcMAC: '00:1B:44:11:3A:B7',
                        dstMAC: '00:00:5E:00:01:01',
                        vlan: '100',
                        alertID: '20250402_abcd1234',
                        username: 'user',
                        password: '********'
                    },
                    // 更多类似结构...
                    {
                        firstOccurrence: '2025-04-02 10:12:00',
                        lastOccurrence: '2025-04-02 12:00:00',
                        victimIP: '10.10.10.10',
                        attackerIP: '1.1.1.1',
                        assetIP: '10.10.10.10',
                        level1Type: '攻击利用',
                        level2Type: 'WebShell',
                        threatName: '疑似webshell通信',
                        ioc: '0x7f3a',
                        attackResult: '成功',
                        threatLevel: '高危',
                        count: 1,
                        attackStage: '渗透',
                        assetGroup: 'DMZ资产组',
                        xffProxy: '',
                        uri: '',
                        cascadeUnit: '总部',
                        status: '已处置',
                        hostDomain: 'example.com',
                        source: 'WAF',
                        attackOrg: 'Lazarus Group',
                        attackMethod: 'webshell上传',
                        httpStatus: '200',
                        attackDimension: '外部攻击',
                        isWhitelist: '否',
                        payload: '恶意载荷内容...',
                        requestHeader: '{ "Referer": "" }',
                        requestBody: 'cmd=id',
                        responseHeader: '{ "Location": "/redirect.php" }',
                        responseBody: 'root:x:0:0::/root:/bin/bash',
                        webshellContent: '',
                        responsiblePerson: '王五',
                        assetTags: '业务系统',
                        assetName: 'Web_Server',
                        isKeyFocus: '是',
                        attackerGeo: '新加坡',
                        eventReported: '已上报',
                        isRead: '未读',
                        attackerAssetGroup: '外部IP',
                        victimAssetGroup: '内部IP',
                        alertTags: '紧急',
                        srcIP: '10.10.10.10',
                        dstIP: '1.1.1.1',
                        srcPort: 50001,
                        dstPort: 80,
                        protocol: 'tcp',
                        srcMAC: '00:1B:44:11:3A:B7',
                        dstMAC: '00:00:5E:00:01:01',
                        vlan: '100',
                        alertID: '20250402_abcd1234',
                        username: 'user',
                        password: '********'
                    },
                    // 更多类似结构...
                    {
                        firstOccurrence: '2025-04-02 10:12:00',
                        lastOccurrence: '2025-04-02 12:00:00',
                        victimIP: '10.10.10.10',
                        attackerIP: '1.1.1.1',
                        assetIP: '10.10.10.10',
                        level1Type: '攻击利用',
                        level2Type: 'WebShell',
                        threatName: '疑似webshell通信',
                        ioc: '0x7f3a',
                        attackResult: '成功',
                        threatLevel: '高危',
                        count: 1,
                        attackStage: '渗透',
                        assetGroup: 'DMZ资产组',
                        xffProxy: '',
                        uri: '',
                        cascadeUnit: '总部',
                        status: '已处置',
                        hostDomain: 'example.com',
                        source: 'WAF',
                        attackOrg: 'Lazarus Group',
                        attackMethod: 'webshell上传',
                        httpStatus: '200',
                        attackDimension: '外部攻击',
                        isWhitelist: '否',
                        payload: '恶意载荷内容...',
                        requestHeader: '{ "Referer": "" }',
                        requestBody: 'cmd=id',
                        responseHeader: '{ "Location": "/redirect.php" }',
                        responseBody: 'root:x:0:0::/root:/bin/bash',
                        webshellContent: '',
                        responsiblePerson: '王五',
                        assetTags: '业务系统',
                        assetName: 'Web_Server',
                        isKeyFocus: '是',
                        attackerGeo: '新加坡',
                        eventReported: '已上报',
                        isRead: '未读',
                        attackerAssetGroup: '外部IP',
                        victimAssetGroup: '内部IP',
                        alertTags: '紧急',
                        srcIP: '10.10.10.10',
                        dstIP: '1.1.1.1',
                        srcPort: 50001,
                        dstPort: 80,
                        protocol: 'tcp',
                        srcMAC: '00:1B:44:11:3A:B7',
                        dstMAC: '00:00:5E:00:01:01',
                        vlan: '100',
                        alertID: '20250402_abcd1234',
                        username: 'user',
                        password: '********'
                    },
                    // 更多类似结构...
                    {
                        firstOccurrence: '2025-04-02 10:12:00',
                        lastOccurrence: '2025-04-02 12:00:00',
                        victimIP: '10.10.10.10',
                        attackerIP: '1.1.1.1',
                        assetIP: '10.10.10.10',
                        level1Type: '攻击利用',
                        level2Type: 'WebShell',
                        threatName: '疑似webshell通信',
                        ioc: '0x7f3a',
                        attackResult: '成功',
                        threatLevel: '高危',
                        count: 1,
                        attackStage: '渗透',
                        assetGroup: 'DMZ资产组',
                        xffProxy: '',
                        uri: '',
                        cascadeUnit: '总部',
                        status: '已处置',
                        hostDomain: 'example.com',
                        source: 'WAF',
                        attackOrg: 'Lazarus Group',
                        attackMethod: 'webshell上传',
                        httpStatus: '200',
                        attackDimension: '外部攻击',
                        isWhitelist: '否',
                        payload: '恶意载荷内容...',
                        requestHeader: '{ "Referer": "" }',
                        requestBody: 'cmd=id',
                        responseHeader: '{ "Location": "/redirect.php" }',
                        responseBody: 'root:x:0:0::/root:/bin/bash',
                        webshellContent: '',
                        responsiblePerson: '王五',
                        assetTags: '业务系统',
                        assetName: 'Web_Server',
                        isKeyFocus: '是',
                        attackerGeo: '新加坡',
                        eventReported: '已上报',
                        isRead: '未读',
                        attackerAssetGroup: '外部IP',
                        victimAssetGroup: '内部IP',
                        alertTags: '紧急',
                        srcIP: '10.10.10.10',
                        dstIP: '1.1.1.1',
                        srcPort: 50001,
                        dstPort: 80,
                        protocol: 'tcp',
                        srcMAC: '00:1B:44:11:3A:B7',
                        dstMAC: '00:00:5E:00:01:01',
                        vlan: '100',
                        alertID: '20250402_abcd1234',
                        username: 'user',
                        password: '********'
                    },
                    // 更多类似结构...
                    {
                        firstOccurrence: '2025-04-02 10:12:00',
                        lastOccurrence: '2025-04-02 12:00:00',
                        victimIP: '10.10.10.10',
                        attackerIP: '1.1.1.1',
                        assetIP: '10.10.10.10',
                        level1Type: '攻击利用',
                        level2Type: 'WebShell',
                        threatName: '疑似webshell通信',
                        ioc: '0x7f3a',
                        attackResult: '成功',
                        threatLevel: '高危',
                        count: 1,
                        attackStage: '渗透',
                        assetGroup: 'DMZ资产组',
                        xffProxy: '',
                        uri: '',
                        cascadeUnit: '总部',
                        status: '已处置',
                        hostDomain: 'example.com',
                        source: 'WAF',
                        attackOrg: 'Lazarus Group',
                        attackMethod: 'webshell上传',
                        httpStatus: '200',
                        attackDimension: '外部攻击',
                        isWhitelist: '否',
                        payload: '恶意载荷内容...',
                        requestHeader: '{ "Referer": "" }',
                        requestBody: 'cmd=id',
                        responseHeader: '{ "Location": "/redirect.php" }',
                        responseBody: 'root:x:0:0::/root:/bin/bash',
                        webshellContent: '',
                        responsiblePerson: '王五',
                        assetTags: '业务系统',
                        assetName: 'Web_Server',
                        isKeyFocus: '是',
                        attackerGeo: '新加坡',
                        eventReported: '已上报',
                        isRead: '未读',
                        attackerAssetGroup: '外部IP',
                        victimAssetGroup: '内部IP',
                        alertTags: '紧急',
                        srcIP: '10.10.10.10',
                        dstIP: '1.1.1.1',
                        srcPort: 50001,
                        dstPort: 80,
                        protocol: 'tcp',
                        srcMAC: '00:1B:44:11:3A:B7',
                        dstMAC: '00:00:5E:00:01:01',
                        vlan: '100',
                        alertID: '20250402_abcd1234',
                        username: 'user',
                        password: '********'
                    }
                ]
            });
        }, 300);
    });
};